experimentName: Experiment
trialConcurrency: 1
maxExperimentDuration: 1d
maxTrialNumber: 1000
searchSpaceFile: E:\programing\workspace\TCAD2024\TCAD\benchmarks\search_space.json
useAnnotation: false
trialCommand: python C3.py
trialCodeDirectory: E:\programing\workspace\TCAD2024\TCAD\benchmarks
trialGpuNumber: 0
tuner:
  name: TPE
  classArgs:
    optimize_mode: maximize
trainingService:
  platform: local